### ISSUE TITLE
Cache time?

### ISSUE THREAD

**Issue by WaterXCubic** [Bertware/bukkitgui2#84]
I am using the bukkit gui v1.8.0.541 
and some player at the player list doesn't show their skin and shows the default skin Steve?
Is there a way to solve this?

**Comment by WaterXCubic** [comment]
I have search it on google and someone say that its the cache of the API that give the face of it?
Is it true?

**Comment by Bertware** [comment]
It might take a couple of hours before a player skin is updated.
Unregistered (cracked) player skins might vary.
Furthermore, the network request might've failed, or there might have gone something wrong in the API. I can't really do much about this right now, since as long as "some" skins work, this means the GUI to API part works.

**Comment by WaterXCubic** [comment]
Is the API minotar.net?

**Comment by WaterXCubic** [comment]
Can you change the API to other API that u can also retrieve the skin??
I have a idea
Have a look at this
https://mcapi.ca/pages/docs/avatar
And use this plzz
https://mcapi.ca/avatar/2d/****

**Comment by Bertware** [comment]
Minotar has proven to still work during a recent stress-test for the GUI.
Maybe there was a short outage, but it's working now.

The project isn't abandoned, but I don't have that much time. However, since all the source code is available here, everyone can make fixes or add features.
